spin_manifest_version = "1"
authors = ["Matheus Cardoso <matheus@cardo.so>"]
description = "Spinlets registry"
name = "spinlet-registry"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spinlet-registry"
source = "../target/wasm32-wasi/release/spinlet_registry.wasm"
files = [{ source = ".spinlet", destination = "/" }]
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]