[access.stdio]
stdin = true
stdout = true
stderr = true

[[access.env]]
key = "HOME"

[[access.dir]]
path = "."
read = true

[[access.file]]
path = "Cargo.toml"
read = true

[[access.dir]]
path = "registry"
read = true

[[access.file]]
path = "registry/spin.toml"
read = true
write = true

