[hook.build.after]
enabled = true

[[access.fs.dir]]
path = "."
read = true
[access.env.var]
keys = ["HOME"]
[access.env.args]
enabled = true
[access.io.stdin]
enabled = true
[access.io.stdout]
enabled = true
[access.io.stderr]
enabled = true
