[workspace]
members = ["spinlets"]

[package]
name = "spinlet"
version = "0.1.0"
edition = "2021"
authors = ["Matheus Cardoso <matheus@cardo.so>"]

[dependencies]
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt" ]}
clap = { version = "4", features = ["unicode", "env", "derive", "cargo", "string", "unstable-v5", "wrap_help", "unstable-styles"] }
tokio = { version = "1", features = ["full"] }
lazy_static = "1"
dirs = "5"
cap-std = "1"
cap-rand = "1"
cap-fs-ext = "1"
cap-net-ext = "1"
anyhow = "1"
thiserror = "1"
tracing = "0.1"

fs-set-times = "0.19"
cap-time-ext = "1"
bitflags = "2"
windows-sys = "0.48"
rustix = "0.37"
async-trait = "0.1"
io-lifetimes = { version = "1", default-features = false }
once_cell = "1.12.0"
system-interface = { version = "0.25", features = ["cap_std_impls"] }
wit-bindgen = { version = "0.6", default-features = false }
itertools = "0.10"
ipnet = "2"
tempfile = "3"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", features = ["component-model"] }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime", features = ["tokio"] }
wasmtime-wasi-http = { git = "https://github.com/bytecodealliance/wasmtime" }
reqwest = "0.11"