name = "spinlet"
version = "0.2.0"
repository = "https://github.com/cardoso/spinlet"

default = "shell"

root = ".spinlet"
etc = "etc"
etc_ext = "toml"
bin = "bin"
bin_ext = "wasm"
lib = "lib"
lib_ext = "wasm"

[alias]
add = "spin add"
build = "spin build"
cloud = "spin cloud"
deploy = "spin deploy"
help = "spin help"
login = "spin login"
new = "spin new"
plugins = "spin plugins"
registry = "spin registry"
templates = "spin templates"
up = "spin up"
watch = "spin watch"