[[access.fs.dir]]
path = "."
read = true

[access.env.var]
keys = []

[access.env.args]
enabled = true

[access.io.stdin]
enabled = true
[access.io.stdout]
enabled = true
[access.io.stderr]
enabled = true
